import { OnWorkerEvent, Processor, WorkerHost } from '@nestjs/bullmq';
import { Injectable, Logger } from '@nestjs/common';
import { EmailQueues } from 'src/libraries/queues/queue.constants';
import { Job, Queue } from 'bullmq';
import {
  JobPriority,
  PostCreatedJob,
  QueueEventJobPattern,
  UnsafePostAlertJob,
  UserAccountBlockAlertJob,
  UserBannedAdminNotificationJob,
} from 'src/libraries/queues/jobs';

import { ConfigService } from '@nestjs/config';
import mongoose from 'mongoose';
import { TextSentimentAnalysisService } from '../services/text-sentiment-analysis.service';
import { PostService } from 'src/app/post/post.service';
import { InjectContentModerationNotificationQueue } from 'src/libraries/queues/decorators/inject-queue.decorator';
import { UserService } from 'src/app/user/user.service';
@Processor(EmailQueues.CONTENT_MODERATION_QUEUE, {
  concurrency: 100,
  useWorkerThreads: true,
})
@Injectable()
export class ContentModerationProcessors extends WorkerHost {
  private readonly logger = new Logger(ContentModerationProcessors.name);
  private readonly NEGATIVE_THRESHOLD: number;
  private readonly UNSAFE_POST_COUNT_THRESHOLD: number;
  constructor(
    private _configService: ConfigService,
    private _postService: PostService,
    private _userService: UserService,
    private _textSentimentAnalysisService: TextSentimentAnalysisService,
    @InjectContentModerationNotificationQueue()
    private _contentModerationNotificationQueue: Queue,
  ) {
    super();
    this.NEGATIVE_THRESHOLD =
      this._configService.get<number>('NEGATIVE_THRESHOLD');
    this.UNSAFE_POST_COUNT_THRESHOLD = this._configService.get<number>(
      'UNSAFE_POST_COUNT_THRESHOLD',
    );
  }
  async process(
    job: Job<PostCreatedJob['data'], number, string>,
  ): Promise<void> {
    try {
      switch (job.name) {
        case QueueEventJobPattern.POST_CREATED:
          await this.checkPostContent(job);
          break;
        default:
          break;
      }
    } catch (error) {
      this.logger.error(
        `Failed to process job ${job.id}: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  async checkPostContent(job: Job<PostCreatedJob['data']>) {
    const { postId } = job.data;
    try {
      // fetching the post content by postId
      const post = await this._postService.getPostById(
        new mongoose.Types.ObjectId(postId),
      );

      if (!post) {
        throw new Error(`Post with id ${postId} not found`);
      }

      // analysis of the post content sentiments score
      const { sentiments, isSafe } =
        await this._textSentimentAnalysisService.analyzeTextSentiment(
          post.content,
        );
      this.logger.debug(sentiments, isSafe);
      if (!isSafe) {
        // updating the post is_safe property so post will not recommend in feed
        await this._postService.updatePostIsSafeById(
          new mongoose.Types.ObjectId(postId),
          isSafe,
        );
        // find user of the post by userId

        const user = await this._userService.findById(post.userId);

        const notificationEventData: UnsafePostAlertJob['data'] = {
          email: user.gbpuatEmail,
          username: user.username,
        };
        // trigger the event for notification user regarding the unsafe post generated by user..
        await this._contentModerationNotificationQueue.add(
          QueueEventJobPattern.CONTENT_MODERATION_NOTIFICATION_FOR_USER,
          { ...notificationEventData },
          {
            priority: JobPriority.HIGH,
          },
        );

        // and check how many post of the same user has already marked as unsafe in last 10 days.
        const unsafePostCount =
          await this._postService.getUnsafePostCountOfUser(post.userId);

        if (unsafePostCount > this.UNSAFE_POST_COUNT_THRESHOLD) {
          // marked user as permanent bloacked

          await this._userService.markUserAsPermanentBlock(post.userId);

          const notificationForUserBlockEventData: UserAccountBlockAlertJob['data'] =
            {
              email: user.gbpuatEmail,
              username: user.username,
            };
          // trigger event for sending the user a email for notifying its account blocking activity
          await this._contentModerationNotificationQueue.add(
            QueueEventJobPattern.CONTENT_MODERATION_NOTIFICATION_ACCOUNT_BLOCKED_FOR_USER,
            { ...notificationForUserBlockEventData },
            {
              priority: JobPriority.HIGHEST,
            },
          );
          // find all the admins
          const admins = await this._userService.findAdmins();

          for (const admin of admins) {
            const userBannedAdminNotificationEventData: UserBannedAdminNotificationJob['data'] =
              {
                email: admin.gbpuatEmail,
                firstName: admin.firstName,
                bannedUsername: user.username,
              };

            // trigger the event for notifiying the admins regarding blocking of user
            await this._contentModerationNotificationQueue.add(
              QueueEventJobPattern.CONTENT_MODERATION_NOTIFICATION_ACCOUNT_BLOCKED_FOR_ADMIN,
              { ...userBannedAdminNotificationEventData },
              {
                priority: JobPriority.HIGHEST,
              },
            );
          }
        }

        // if the post count are more than 5 then permanent block the user
        //  and notify to the admin mail
      } else {
        this.logger.log(`Post with postId: ${postId} is safe.`);
      }
    } catch (error) {
      this.logger.error(
        `Error checking post content for job ${job.id}: ${error.message}`,
        error.stack,
      );
      throw error;
    }
  }

  @OnWorkerEvent('completed')
  async onCompleted(job: Job<PostCreatedJob['data']>) {
    const { id, name, queueName, finishedOn } = job;
    const completionTime = finishedOn ? new Date(finishedOn).toISOString() : '';

    this.logger.log(
      `Job id: ${id}, name: ${name} completed in queue ${queueName} on ${completionTime}.`,
    );
  }

  @OnWorkerEvent('progress')
  onProgress(job: Job) {
    const { id, name, progress } = job;
    this.logger.log(`Job id: ${id}, name: ${name} completes ${progress}%`);
  }

  @OnWorkerEvent('failed')
  onFailed(job: Job) {
    const { id, name, queueName, failedReason } = job;
    this.logger.error(
      `Job id: ${id}, name: ${name} failed in queue ${queueName}. Failed reason: ${failedReason}`,
    );
  }

  @OnWorkerEvent('active')
  onActive(job: Job) {
    const { id, name, queueName, timestamp } = job;
    const startTime = timestamp ? new Date(timestamp).toISOString() : '';
    this.logger.log(
      `Job id: ${id}, name: ${name} starts in queue ${queueName} on ${startTime}.`,
    );
  }
}
